### PR TITLE
Transactions

### PR DESCRIPTION
**Pull request by mikeholmesuk**
Request to include transaction namespace into Clarango library for ading rtansaction support. Response to #17 on Clarango.

### CODE REVIEW

**Comment by Lepetere** [comment]
This merge request also contains the commits that are supposed to be merged with https://github.com/edlich/clarango/pull/20. I'm not going to merge this right away because that is still point of discussion.

Also again with this new namespace I'm wondering: Do we really want another namespace for a single new function? How do you like the idea of putting this into the `misc` namespace (which currently also only has one function)?

**Comment by mikeholmesuk** [comment]
Apologies, I didn't realise this has #20 in it as well. Consider that a git fail on my part. I'll fix that and push another request. As for the additional namespace, my comments in #20 are still relevant so I won't repeat them here :) Needless to say, I'm not especially invested in where this goes as long as the functions are available.

**Comment by mikeholmesuk** [comment]
I've updated the branch to include just the two files (src and test) for this change. Apologies for the mix-up.

As a follow on to my shorter answers yesterday, could I elaborate a little more on my stance on namespaces? 

Primarily I'm approaching this as a user of the library and consequently of ArangoDB itself. Personally I don't mind having multiple require statements in to pull in multiple facets of a given library. Yes, it's quite nice to have a single thing to require but I generally think that only really works when the thing that is being required in has a limited and/or focussed purpose. As an application/ service developer I don't mind having a few imports if it means I can cherry pick the features that I need to use, and if one were concerned with having to manage dozens of require statements due to using dozens of different features then it might be fairly prudent to apply the counter argument of 'your own namespaces are doing too much', irrespective of the underlying library. 

My preference for separating the features into separate namespaces in this instance is three fold. 

Firstly, it marries up with how ArangoDB have arranged their end-points and, by logical extension, their functionality. We may not agree on how they have split them or the respective design decisions they have taken in doing so, but they are where they are. Splitting the features of clarango into namespaces that match these end-points means that there is less of a barrier for a user of the library using this to work with ArangoDB. One could look at the ArangoDB API and see the appropriate end-point for the task at hand and start delving in there knowing exactly where the equivalent functions are available in clarango. The same works in reverse. 

Secondly, it enables users to cherry pick features that they will use for what they need to do. Yes, transaction only has one function in there, but that (to me at least) is OK because that is all that it does; transactions.

Finally, coming from the angle of a contributor or a user (of which I am both), the library being more modular means that it is arguably easier to understand the code due to less noise, but also makes the tests more concise and focussed. This means that it is easier to change one aspect of the library knowing that it won't (shouldn't?) impact others, but also means that it is easier to understand how the library should be used (in case that can't be ascertained from the docs).

Failing that if we wanted to have the best of both worlds (modular code, but a simplified public API) then maybe [Potemkin](https://github.com/ztellman/potemkin) could be an option?

As I said previously though, I'm happy to support whichever way you guys would like to take the library. I'm opinionated but not inflexible :) . It would be good to decide how you would like to manage the future of the library though so that potential contributors are clear on how to work with it. I have a few features that I'd like to add as well so it would be good to clear up how we should work on this. I'm happy to contribute whichever way you guys decide to go.

**Comment by Lepetere** [comment]
I'll take a closer look at Potemkin tomorrow.

For now my viewpoint is this: Yes I agree, having the same namespaces as in the ArangoDB HTTP API provides a certain transparency. But I wrote the library with a user in mind who didn't actually read the ArangoDB HTTP api docs and *shouldn't have to* in order to use the library. It should be clear just from the documentation of Clarango how to use it with the database. Coming from that point I applied my own views on how to group the available namespaces so that we don't end up with too many namespaces, but also don't combine functions which are too different from each other. I wanted it to be intuitively clear from the names of the namespaces which one you have to require for a certain functionality.

Also consider that now we already have Clarango namespaces which combine ArangoDB HTTP api namespaces.

But I have to say that I also see your point. I agree that transactions can be it's own namespace because it's a whole thing of it's own. But then the AQL functions I still think they also could fit into the already existing `query` namespace. Would you agree on taking this middle path?

**Comment by mikeholmesuk** [comment]
Hey. Fair enough, I can see both viewpoints and ultimately it is your library so I absolutely wouldn't want to dictate the structure, philosophy etc. Happy to take whichever path but the middle one sounds very reasonable indeed. Shall I make the necessary amendments to move the `aql-function` pieces to `query` and update the pull request? 

Also, given the eminently healthy debate around this, do you think it is worth raising any proposed changes as issues so they can be discussed and agreed prior to being implemented?

**Comment by Lepetere** [comment]
Yes if you feel like making the changes, please go ahead :) I'll merge the transactions then right away.

Also yes, if you feel there is anything more to be discussed, feel free to open issues about it.

**Pull request merged**
